name: Code Lint
on:
  pull_request:
    types: [ opened, reopened ]
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pylint

      - name: Run pre-commit
        env:
          SKIP: mypy,no-commit-to-branch
        run: pre-commit run --all-files
